apiVersion: gateway.k8s.aws/v1beta1
kind: LoadBalancerConfiguration
metadata:
  name: my-alb-config
  namespace: default
spec:
  scheme: internet-facing
  ipAddressType: ipv4
  listeners:
    https:
      certificates:
      - certificateARN: arn:aws:acm:us-east-1:764694154057:certificate/f0c607ab-0842-499b-b461-19e3ed3208d5